### ISSUE TITLE
symfony/console v3

### ISSUE THREAD

**Issue by Awnage** [enygma/expose#55]
Need to update reqs to support symfony/console 3. Current setup makes this difficult on Laravel (and probably others)

    composer require enygma/expose:dev-master

**Comment by enygma** [comment]
Are you just saying it needs a new release or that this needs to be updated in master?

**Comment by Awnage** [comment]
Needs an update and testing in master. Our current `composer.json`

    "symfony/console": "~2.1"

Gives us all consoles < 3.0. Some projects are using console 3 now (like laravel). Alas it is not too simple, as console 3.05 requires php: >=5.5.9 so we would need to update the docs to specify a different minimum php version. 

Also, I have not checked if there are interface changes between 2 & 3, so things may break horribly.

**Comment by colinodell** [comment]
I've tested using `~2.1|~3.0` as the constraint.  When 3.0 is installed, all unit tests pass and the FilterCommand works fine.

The ProcessQueueCommand does not work, but those same failure issues seem to exist regardless of whether you're using 2.1 or 3.0:

 - InputOptions are defined as not using values (`VALUE_NONE` instead of `VALUE_REQUIRED`)
 - The command uses `!== false` to check if an option is provided. However, Symfony returns `null` in these cases.
 - Line 138 attempts to call `listQueue()` on the command class, but this method does not exist.

Also, according to the [CHANGELOG](https://github.com/symfony/console/blob/master/CHANGELOG.md), there only seems to be one breaking change between 2.1 and 3.0, but this project does not appear to be impacted.

So I think you should be okay to bump the constraint.
